config/routes.rb
TDList::Application.routes.draw do
  get "lists/index"
  
  resources :lists
  resources :tasks 

  #match :name => 'tasks#index', :as => 'list_tasks'
  
  root :to => 'lists#index'

  # See how all your routes lay out with "rake routes"
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :list_status
  validates_presence_of :name, :list_status

  has_many :tasks, dependent: :destroy

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :task_status, :list_id
  validates_presence_of :description, :task_status, :list_id

  belongs_to :list

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]

  # GET /lists
  def index
    @lists = List.all

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @lists }
    end
  end

  # GET /lists/1
  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
    @tasks = @list.tasks
  end

  # POST /lists
  def create
    @list = List.new(params[:list])

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /lists/1
  def update
    @list = List.find(params[:id])
    if @list.update(params[:list])
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /lists/1
  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_url, notice: 'List was successfully destroyed.'
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]

  # GET /tasks
  def index
    @tasks = Task.all

  end

  # GET /tasks/1
  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks

  end

  # GET /tasks/new
  def new
    @task = Task.new(params[:id])
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    @list = List.find(@task.list_id)
  end

  # POST /tasks
  def create
    @task = Task.new(params[:task])

    if @task.save
      redirect_to @task.list, notice: 'Task was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /tasks/1
  def update
    @task = Task.find(params[:id])
    if @task.update(params[:task])
      redirect_to @task.list, notice: 'Task was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /tasks/1
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to @task.list, notice: 'Task was successfully destroyed.'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>TDList</title>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "bootstrap" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="page-header">
      <h1><%= link_to "Task Lists", root_path %>
        <small>Rails Girls Atlanta Project</small>
      </h1>
    </div>

    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :name, :label => 'Title of List' %>
  <%= f.input :list_status, :default => ['In Progress'], collection: ['In Progress', 'Completed']%>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h3>Edit List : <%= link_to @list.name, task_path(@list.id) %> </h3>

<h4> With Tasks : 
  <% if @tasks.empty? %>
      none
  <% else %>
		<% @tasks.each do |t| %>
      <small>
			<%= t.description %>
      </small>
		<% end %>
  <% end %>

  <br>
 <%= button_to 'Delete List', @list, method: :delete %>
</h4>

<legend></legend>
<%= render 'form' %>

app/views/lists/index.html.erb
<tbody>
  <div class="new">
	 <%= link_to 'Create New List', new_list_path %>
  </div>
  <div class="new" id="notice"><%= notice %>
  </div>

  <div>
    <% @lists.each do |list| %>
      <h3>
        <span style="color:#999999"> - </span>  
        <%= link_to list.name, list %> 
        <small style="color:#999999"><%=list.list_status%></small>
      </h3>
     <% end %>
  </div>
</tbody>

app/views/lists/new.html.erb
<h3>Create New List</h3>

<legend></legend>
<%= render 'form' %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @list.name %> 
  <small> <%= @list.list_status %></small> 
  <small><%= link_to 'Edit List', edit_list_path(@list) %></small> 
</h3>


<table class="table table-striped">
  <thead>
    <tr>
      <td><%= link_to "Create New Task", new_task_path %></td>
    </tr>
    <tr>
      <th>Task Description</th>
      <th>Status</th>
    </tr>
    <legend></legend>
  <% @tasks.each do |t| %>
  <tbody>
    <td><%= link_to t.description, edit_task_path(t) %></td>
    <td><%= link_to t.task_status, edit_task_path(t) %></td>
  </tbody>
  <% end %>
</table>

app/views/tasks/_edit_form.html.erb
<%= simple_form_for @task  do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.association :list, :label => 'Select List' %>
  <%= f.input :description, :label => 'Task Description' %>
  <%= f.input :task_status, :default => ['In Progress'], collection: ['In Progress', 'Completed']%>
  <%= f.button :submit %>

<% end %>

app/views/tasks/_new_form.html.erb
<%= simple_form_for(@task)  do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.association :list, :label => 'Select List', :default => [] %>
  <%= f.input :description, :label => 'Task Description' %>
  <%= f.input :task_status, :default => ['In Progress'], collection: ['In Progress', 'Completed']%>
  <%= f.button :submit %>

<% end %>

app/views/tasks/edit.html.erb
<h3>Edit Task : <%= link_to @task.description, task_path(@list.id) %> 
	<small><%= @task.task_status %></small></h3>

<h4> In List <%= link_to @list.name, task_path(@list.id) %> 
	<br>
 	<%= button_to 'Delete Task', @task, method: :delete %>
 </h4>

<legend></legend>
<%= render 'edit_form' %>

app/views/tasks/new.html.erb
<h3>Create New Task</h3>

<legend></legend>
<%= render 'new_form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<h3><%= @list.name %> 
  <small> <%= @list.list_status %></small> 
  <small><%= link_to 'Edit List', edit_list_path(@list) %></small> 
</h3>


<table class="table table-striped">
  <thead>
    <tr>
      <td><%= link_to "Create New Task", new_task_path %></td>
    </tr>
  	<tr>
  		<th>Task Description</th>
  		<th>Status</th>
  	</tr>
    <legend></legend>
  <% @tasks.each do |t| %>
  <tbody>
    <td><%= link_to t.description, edit_task_path(t) %></td>
    <td><%= link_to t.task_status, edit_task_path(t) %></td>
  </tbody>
  <% end %>
</table>